name: C2ME Test

on:
  push: {}
  pull_request: {}

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        testTask: [runTestC2MEServer]

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        submodules: true

    - name: Set up JDK 21
      uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: 22
        java-package: jdk

    - name: Install LLVM
      uses: KyleMayes/install-llvm-action@v2
      with:
        version: "18.1.8"

    - name: Install required dependencies
      run: sudo apt install libtinfo5

    - uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
          ./.gradle/loom-cache
        key: ${{ runner.os }}-gradle4-test-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle4-test-
        
    - name: Test C2ME
      run: |
        ./gradlew clean ${{ matrix.testTask }}
